# Uncomment this line to define a global platform for your project
platform :ios, '13.0' # Define la plataforma iOS mínima requerida.

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true' # Deshabilita el envío de estadísticas de CocoaPods para mejorar la latencia.

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup # Configuración básica de CocoaPods para Flutter.

target 'Runner' do
  use_frameworks! # Habilita el uso de frameworks.
  use_modular_headers! # Habilita encabezados modulares.

  # Agrega tus pods aquí.
  pod 'Google-Mobile-Ads-SDK' # Pod para el SDK de Google Mobile Ads.

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__)) # Instala todos los pods de Flutter.
  
  target 'RunnerTests' do
    inherit! :search_paths # Hereda rutas de búsqueda para los tests.
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= [
        '$(inherited)',
        '${PODS_ROOT}/**',
        '${PODS_XCFRAMEWORKS_BUILD_DIR}/**',
        '${PODS_CONFIGURATION_BUILD_DIR}/**'
      ]
      ['OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |flag|
        flags = config.build_settings[flag]
        if flags.is_a?(String)
          flags = flags.split(' ')
        end
        if flags.is_a?(Array)
          flags = flags.reject { |f| f == '-G' }
          config.build_settings[flag] = flags.empty? ? nil : flags
        end
      end
    end
  end
end
